feat: Create release notes before release

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -129,7 +129,22 @@ cli_test:
   script: |
     docker buildx bake cli-test
 
+release_notes:
+  rules:
+  - if: $CI_COMMIT_TAG =~ /^v/
+  variables:
+    GIT_DEPTH: 0
+    GLAB_SEND_TELEMETRY: 0
+  script: |
+    glab auth login --hostname="${CI_SERVER_HOST}" --job-token="${CI_JOB_TOKEN}"
+    bash scripts/release-notes-gitlab.sh >release-notes.md
+  artifacts:
+    paths:
+    - release-notes.md
+
 release:
+  needs:
+  - release_notes
   extends:
   - .docker
   - .docker:dind
@@ -141,6 +156,10 @@ release:
   variables:
     GIT_DEPTH: 0
   script: |
+    if ! test -s release-notes.md; then
+      echo "Release notes not found"
+      exit 1
+    fi
     docker buildx build \
         --target=publish-gitlab \
         --build-arg=CI_SERVER_HOST \
@@ -148,9 +167,6 @@ release:
         --build-arg=GITLAB_TOKEN \
         --build-arg=SIGSTORE_ID_TOKEN \
         .
-  artifacts:
-    paths:
-    - release-notes.md
 
 prepare:
   needs:
